name: 'yanskun/slack-file-upload-action'
description: "GitHub Action for uploading a file to Slack"
author: "yanskun"
branding:
  icon: file
  color: orange

inputs:
  token:
    description: Slack Bot Token
    required: true
  path:
    description: file path
    required: true
  channel_id:
    description: Slack Channel ID
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
